callbacks:
  early_stopping:
    class_name: pl.callbacks.EarlyStopping
    params:
      monitor: ${training.metric}
      patience: 80
      mode: ${training.mode}

  model_checkpoint:
    class_name: pl.callbacks.ModelCheckpoint
    params:
      monitor: ${training.metric}
      save_top_k: 3
      filepath: saved_models/{epoch}_{c_dice:.4f}
      mode: ${training.mode}
  
  ckpt_callback:
    class: utils.utils.Last20ModelCheckpoint
