exp:
  image: ['SE2.nii.gz']
  segmentation: ['segmentation.nii.gz']
  cid_prefix: ''
  patch_dir: tsukuba_96x96x8
  train_ids: ['001', '002', '003', '007', '008', '009', '010', '013', '015', '017', '018', '019', '021', '022', '023', '024', '026', '029', '033', '035', '036', '039', '053', '055', '063', '065', '067', '068', '069', '074', '077', '082', '083', '088', '090', '093', '094', '095', '096', '097', '102', '103', '104', '105', '107', '109', '112', '113', '123', '126', '134', '154', '157']
  val_ids: ['004', '045', '122', '125', '127', '135', '140', '142', '149', '150']
  test_ids: ['005', '011', '028', '037', '038', '046', '062', '072', '124', '146']
  overlap: [1,1,4]
  size: [96,96,8]
  gpus: 2
  epoch: 500
  lr: 0.003
  batch_size: 8
  pred_batch_size: 8
  nlabels: 4
  input_channel: 
  step_size: 200
  path_parser: get_1timephase_paths
  parse_timephase: ['image_SE2']
  ckpt_callback: 
    class: src.utils.Last20ModelCheckpoint
  loss: 
    class: src.loss.BCEDiceLoss
    params:
      alpha: 0.5
      beta: 0.5
  net:
    class: model.unet.UNet3D
    params:
      input_channel: 1
      n_classes: 4      
  augment:
    train:
      RandomFlip: {}
      RandomRotate:
        angle_spectrum: 30
        axes: [[2,1]]
    val: {}
  
