exp:
    image: ['SE2.nii.gz','SE3.nii.gz']
    segmentation: ['segmentation.nii.gz']
    cid_prefix: ''
    patch_dir: tsukuba_48x48x32
    fold: [[127, 9, 33, 69, 37, 103, 10, 125, 149, 63, 22, 93, 8, 142, 151, 134, 104],[124, 68, 150, 53, 95, 135, 140, 97, 107, 18, 94, 28, 65, 38, 112, 46, 45],[96, 5, 154, 122, 157, 15, 90, 19, 2, 17, 13, 74, 83, 11, 39, 109, 82],[3, 21, 77, 126, 113, 62, 55, 14, 146, 72, 123, 67, 88, 29, 4, 105, 102]]
    overlap: [2,2,1]
    size: [48,48,32]
    gpus: 2
    epoch: 500
    lr: 0.003
    batch_size: 12
    pred_batch_size: 16
    nlabels: 4
    fold_strategy: kfold
    input_channel: 
    step_size: 200
    ckpt_callback: 
      class: src.utils.Last20ModelCheckpoint
    loss: 
      class: src.loss.BCEDiceLoss
      params:
        alpha: 0.5
        beta: 0.5
    net:
      class: model.unet.UNet3D
      params:
        input_channel: 2
        n_classes: 4      
    augment:
      train:
        RandomFlip: {}
        RandomRotate:
          angle_spectrum: 30
          axes: [[2,1]]
      val: {}
    